CREATE DATABASE PrestamosDB;
GO

USE PrestamosDB;
GO

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    Role VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Loans (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    InterestRate DECIMAL(5,2) NOT NULL,
    TermMonths INT NOT NULL,
    MonthlyPayment DECIMAL(18,2),
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ApplicationDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    ApprovalDate DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_Loans_Users
        FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Payments (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    LoanId INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentDate DATETIME2 NOT NULL DEFAULT GETDATE(),
    PaymentMethod VARCHAR(50),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_Payments_Loans
        FOREIGN KEY (LoanId) REFERENCES Loans(Id)
);
GO