name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore backend
        run: dotnet restore backend/PrestamosBancarios.sln

      - name: Test backend
        run: dotnet test backend/PrestamosBancarios.sln --no-restore

      - name: Publish backend
        run: dotnet publish backend/PrestamosBancarios.API/PrestamosBancarios.API.csproj -c Release -o publish/backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build